# Generated by Django 2.1.1 on 2020-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='highest_education',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='highest_education_academy',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='current_designation',
            new_name='title',
        ),
        migrations.AddField(
            model_name='experience',
            name='project',
            field=models.TextField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
