# Generated by Django 3.1.2 on 2020-10-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_followrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
