# Generated by Django 3.1.2 on 2020-10-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201023_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
    ]
