# Generated by Django 3.1.2 on 2020-10-23 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201023_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='followrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
