# Generated by Django 3.1.2 on 2020-10-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201028_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('friends', 'friends')], default='pending', max_length=100, verbose_name='status'),
        ),
    ]
